### ISSUE TITLE
Operations dont work. Throws this error in console.

### ISSUE THREAD

**Issue by mkstayalive** [spywhere/Javatar#66]
Organize imports doesn't work. Throws this error in console. I'm on Mac 10.10.4 Yosemite.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "utils.javatar_event_handler in /Users/manish/Library/Application Support/Sublime Text 3/Installed Packages/Javatar.sublime-package", line 290, in on_activated
  File "utils.javatar_event_handler in /Users/manish/Library/Application Support/Sublime Text 3/Installed Packages/Javatar.sublime-package", line 192, in on_activated
  File "Javatar in /Users/manish/Library/Application Support/Sublime Text 3/Installed Packages/Javatar.sublime-package", line 26, in on_change
TypeError: 'NoneType' object is not callable
reloading settings Packages/User/Javatar.sublime-settings
```

**Comment by spywhere** [comment]
Can you give me an Action History after this happen? (via `Cmd+Shift+K, Cmd+Shift+H`)

**Comment by mkstayalive** [comment]
It had happened via `(Cmd+Shift+K, Cmd+Shift+O)`.

I had tried uninstalling and installing back the package. But it didn't work. Now I just disabled the package and enabled it back. Strangely its working fine now.

**Comment by spywhere** [comment]
Ok, I'll close the issue then...
